// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:help_scout_beacon/help_scout_beacon_api.g.dart';


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is HSBeaconRoute) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is HSBeaconFocusMode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is HSBeaconSettings) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is HSBeaconUser) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : HSBeaconRoute.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : HSBeaconFocusMode.values[value];
      case 131: 
        return HSBeaconSettings.decode(readValue(buffer)!);
      case 132: 
        return HSBeaconUser.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Help Scout Beacon API
abstract class TestHelpScoutBeaconApi {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding => TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Initialize the beacon with a beaconId and optional settings
  void setup({required HSBeaconSettings settings});

  /// Signs in with a Beacon user. This gives Beacon access to the user’s name, email address, and signature.
  void identify({required HSBeaconUser beaconUser});

  /// Opens the Beacon SDK from a specific view controller. The Beacon view controller will be presented as a modal.
  void open({required HSBeaconSettings settings, HSBeaconRoute route = HSBeaconRoute.ask, String? parameter, });

  void prefillContactForm(String? subject, String? message, List<String>? attachments);

  /// Logs the current Beacon user out and clears out their information from local storage.
  void clear();

  static void setUp(TestHelpScoutBeaconApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.setup$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.setup was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final HSBeaconSettings? arg_settings = (args[0] as HSBeaconSettings?);
          assert(arg_settings != null,
              'Argument for dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.setup was null, expected non-null HSBeaconSettings.');
          try {
            api.setup(settings: arg_settings!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.identify$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.identify was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final HSBeaconUser? arg_beaconUser = (args[0] as HSBeaconUser?);
          assert(arg_beaconUser != null,
              'Argument for dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.identify was null, expected non-null HSBeaconUser.');
          try {
            api.identify(beaconUser: arg_beaconUser!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final HSBeaconSettings? arg_settings = (args[0] as HSBeaconSettings?);
          assert(arg_settings != null,
              'Argument for dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open was null, expected non-null HSBeaconSettings.');
          final HSBeaconRoute? arg_route = (args[1] as HSBeaconRoute?);
          assert(arg_route != null,
              'Argument for dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open was null, expected non-null HSBeaconRoute.');
          final String? arg_parameter = (args[2] as String?);
          try {
            api.open(settings: arg_settings!, route: arg_route!, parameter: arg_parameter);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.prefillContactForm$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.prefillContactForm was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_subject = (args[0] as String?);
          final String? arg_message = (args[1] as String?);
          final List<String>? arg_attachments = (args[2] as List<Object?>?)?.cast<String>();
          try {
            api.prefillContactForm(arg_subject, arg_message, arg_attachments);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.clear$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          try {
            api.clear();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
