// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsHelpScoutBeaconApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsHelpScoutBeaconApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsHelpScoutBeaconApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashHelpScoutBeaconApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashHelpScoutBeaconApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashHelpScoutBeaconApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Beacon route/screen
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
enum HSBeaconRoute: Int {
  /// Opens to the Home (Ask/Answers) screen (default value)
  case ask = 0
  /// Chat screen
  case chat = 1
  /// Open docs with optional search parameter (requires docs enabled and optionally a search param)
  case docs = 2
  /// Article screen (requires an Article ID and docs enabled)
  case article = 3
  /// Contact form (requires messaging enabled)
  case contactForm = 4
  /// Previous Messages if any exist.
  case previousMessages = 5
}

/// HSBeaconFocusMode represents various configuration modes of Beacon. Allowing you to customize the experience your users have, from getting in contact right away, to a more self service approach.
/// * More info is available AT https://docs.helpscout.com/article/1296-work-with-beacon-modes
enum HSBeaconFocusMode: Int {
  /// An option to see both help articles and contact options side by side
  case neutral = 0
  /// An option to see help articles first and contact options after interacting with content
  case selfService = 1
  /// An option to see contact options first and help articles second
  case askFirst = 2
}

/// Beacon Settings overrides
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
/// * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconSettings.html
///
/// Generated class from Pigeon that represents data sent in messages.
struct HSBeaconSettings: Hashable {
  /// The Beacon ID to use.
  var beaconId: String
  /// Turn Logging on/off (should be disabled in production)
  var debugLogging: Bool
  /// The title used in the main Beacon interface. This is Support by default.
  var beaconTitle: String? = nil
  /// Disable the Docs integration manually if it’s enabled in the Beacon config.
  /// This will not enable Docs if it’s disabled in the config.
  var docsEnabled: Bool? = nil
  /// Disable the contact options manually if it’s enabled in the Beacon config.
  /// This will not enable the contact options if it’s disabled in the config.
  var messagingEnabled: Bool? = nil
  /// Disable the Chat integration manually if it’s enabled in the Beacon config.
  /// This will not enable Chat if it’s disabled in the config.
  var chatEnabled: Bool? = nil
  /// Disable previous messages manually if messaging is enabled in the Beacon config.
  var enablePreviousMessages: Bool
  /// If your Beacon has Docs and Messaging (email or chat) enabled, this mode controls the user experience of the beacon
  var focusMode: HSBeaconFocusMode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HSBeaconSettings? {
    let beaconId = pigeonVar_list[0] as! String
    let debugLogging = pigeonVar_list[1] as! Bool
    let beaconTitle: String? = nilOrValue(pigeonVar_list[2])
    let docsEnabled: Bool? = nilOrValue(pigeonVar_list[3])
    let messagingEnabled: Bool? = nilOrValue(pigeonVar_list[4])
    let chatEnabled: Bool? = nilOrValue(pigeonVar_list[5])
    let enablePreviousMessages = pigeonVar_list[6] as! Bool
    let focusMode: HSBeaconFocusMode? = nilOrValue(pigeonVar_list[7])

    return HSBeaconSettings(
      beaconId: beaconId,
      debugLogging: debugLogging,
      beaconTitle: beaconTitle,
      docsEnabled: docsEnabled,
      messagingEnabled: messagingEnabled,
      chatEnabled: chatEnabled,
      enablePreviousMessages: enablePreviousMessages,
      focusMode: focusMode
    )
  }
  func toList() -> [Any?] {
    return [
      beaconId,
      debugLogging,
      beaconTitle,
      docsEnabled,
      messagingEnabled,
      chatEnabled,
      enablePreviousMessages,
      focusMode,
    ]
  }
  static func == (lhs: HSBeaconSettings, rhs: HSBeaconSettings) -> Bool {
    return deepEqualsHelpScoutBeaconApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHelpScoutBeaconApi(value: toList(), hasher: &hasher)
  }
}

/// Beacon user
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-user/index.html
/// * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconUser.html
///
/// Generated class from Pigeon that represents data sent in messages.
struct HSBeaconUser: Hashable {
  /// The email address for the current user.
  var email: String
  /// The name of the current user.
  var name: String? = nil
  /// The company of the current user. The max length of this value is 60 and will be truncated to fit.
  var company: String? = nil
  /// The job title of the current user. The max length of this value is 60 and will be truncated to fit.
  var jobTitle: String? = nil
  /// The URL to the avatar of the current user. The max length of this value is 200 and will not be set if the absoluteString exceeds that length.
  var avatar: String? = nil
  /// The attributes for the current user. These are arbitrary key/value pairs that will be sent to Help Scout to help identify the current user. You may add up to 30 different attributes.
  var attributes: [AnyHashable?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HSBeaconUser? {
    let email = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let company: String? = nilOrValue(pigeonVar_list[2])
    let jobTitle: String? = nilOrValue(pigeonVar_list[3])
    let avatar: String? = nilOrValue(pigeonVar_list[4])
    let attributes: [AnyHashable?: Any?]? = nilOrValue(pigeonVar_list[5])

    return HSBeaconUser(
      email: email,
      name: name,
      company: company,
      jobTitle: jobTitle,
      avatar: avatar,
      attributes: attributes
    )
  }
  func toList() -> [Any?] {
    return [
      email,
      name,
      company,
      jobTitle,
      avatar,
      attributes,
    ]
  }
  static func == (lhs: HSBeaconUser, rhs: HSBeaconUser) -> Bool {
    return deepEqualsHelpScoutBeaconApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHelpScoutBeaconApi(value: toList(), hasher: &hasher)
  }
}

private class HelpScoutBeaconApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HSBeaconRoute(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HSBeaconFocusMode(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return HSBeaconSettings.fromList(self.readValue() as! [Any?])
    case 132:
      return HSBeaconUser.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HelpScoutBeaconApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HSBeaconRoute {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HSBeaconFocusMode {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? HSBeaconSettings {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? HSBeaconUser {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HelpScoutBeaconApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HelpScoutBeaconApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HelpScoutBeaconApiPigeonCodecWriter(data: data)
  }
}

class HelpScoutBeaconApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HelpScoutBeaconApiPigeonCodec(readerWriter: HelpScoutBeaconApiPigeonCodecReaderWriter())
}

/// Help Scout Beacon API
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HelpScoutBeaconApi {
  /// Initialize the beacon with a beaconId and optional settings
  func setup(settings: HSBeaconSettings) throws
  /// Signs in with a Beacon user. This gives Beacon access to the user’s name, email address, and signature.
  func identify(beaconUser: HSBeaconUser) throws
  /// Opens the Beacon SDK from a specific view controller. The Beacon view controller will be presented as a modal.
  func open(settings: HSBeaconSettings, route: HSBeaconRoute, parameter: String?) throws
  func prefillContactForm(subject: String?, message: String?, attachments: [String]?) throws
  /// Logs the current Beacon user out and clears out their information from local storage.
  func clear() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HelpScoutBeaconApiSetup {
  static var codec: FlutterStandardMessageCodec { HelpScoutBeaconApiPigeonCodec.shared }
  /// Sets up an instance of `HelpScoutBeaconApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HelpScoutBeaconApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialize the beacon with a beaconId and optional settings
    let setupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.setup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! HSBeaconSettings
        do {
          try api.setup(settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setupChannel.setMessageHandler(nil)
    }
    /// Signs in with a Beacon user. This gives Beacon access to the user’s name, email address, and signature.
    let identifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.identify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      identifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let beaconUserArg = args[0] as! HSBeaconUser
        do {
          try api.identify(beaconUser: beaconUserArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      identifyChannel.setMessageHandler(nil)
    }
    /// Opens the Beacon SDK from a specific view controller. The Beacon view controller will be presented as a modal.
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! HSBeaconSettings
        let routeArg = args[1] as! HSBeaconRoute
        let parameterArg: String? = nilOrValue(args[2])
        do {
          try api.open(settings: settingsArg, route: routeArg, parameter: parameterArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let prefillContactFormChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.prefillContactForm\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prefillContactFormChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let subjectArg: String? = nilOrValue(args[0])
        let messageArg: String? = nilOrValue(args[1])
        let attachmentsArg: [String]? = nilOrValue(args[2])
        do {
          try api.prefillContactForm(subject: subjectArg, message: messageArg, attachments: attachmentsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      prefillContactFormChannel.setMessageHandler(nil)
    }
    /// Logs the current Beacon user out and clears out their information from local storage.
    let clearChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.clear\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearChannel.setMessageHandler { _, reply in
        do {
          try api.clear()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearChannel.setMessageHandler(nil)
    }
  }
}
