name: help_scout_beacon
description: "Streamline customer communications in your app with the Help Scout Beacon SDK for Flutter."
version: 0.1.0
repository: https://github.com/coodoo-io/help_scout_beacon
issue_tracker: https://github.com/coodoo-io/help_scout_beacon/issues

topics:
  - customer
  - helpdesk
  - support
  - help

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cross_file: ^0.3.4+2
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^27.1.0

flutter:
  plugin:
    platforms:
      android:
        package: de.coodoo.help_scout_beacon
        pluginClass: HelpScoutBeaconPlugin
      ios:
        pluginClass: HelpScoutBeaconPlugin
      web:
        pluginClass: HelpScoutBeaconWeb
        fileName: src/beacon_web_registrant.dart
