// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum HelpScoutBeaconApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Beacon route/screen
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
enum HSBeaconRoute: Int, CaseIterable {
  /// Opens to the Home (Ask/Answers) screen (default value)
  case ask = 0
  /// Chat screen
  case chat = 1
  /// Open docs with optional search parameter (requires docs enabled and optionally a search param)
  case docs = 2
  /// Article screen (requires an Article ID and docs enabled)
  case article = 3
  /// Contact form (requires messaging enabled)
  case contactForm = 4
  /// Previous Messages if any exist.
  case previousMessages = 5
}

/// HSBeaconFocusMode represents various configuration modes of Beacon. Allowing you to customize the experience your users have, from getting in contact right away, to a more self service approach.
/// * More info is available AT https://docs.helpscout.com/article/1296-work-with-beacon-modes
enum HSBeaconFocusMode: Int, CaseIterable {
  /// An option to see both help articles and contact options side by side
  case neutral = 0
  /// An option to see help articles first and contact options after interacting with content
  case selfService = 1
  /// An option to see contact options first and help articles second
  case askFirst = 2
}

/// Beacon Settings overrides
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
/// * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconSettings.html
///
/// Generated class from Pigeon that represents data sent in messages.
struct HSBeaconSettings: Hashable, CustomStringConvertible {
  /// The Beacon ID to use.
  var beaconId: String
  /// Turn Logging on/off (should be disabled in production)
  ///
  /// Android only: neither the iOS Beacon SDK nor the JS Beacon exposes a logging switch.
  var debugLogging: Bool
  /// The title used in the main Beacon interface. This is Support by default.
  ///
  /// Has no effect on any platform — the title is controlled by the Beacon Builder config.
  /// The iOS SDK deprecated its equivalent property for the same reason.
  var beaconTitle: String? = nil
  /// Disable the Docs integration manually if it’s enabled in the Beacon config.
  /// This will not enable Docs if it’s disabled in the config.
  var docsEnabled: Bool? = nil
  /// Disable the contact options manually if it’s enabled in the Beacon config.
  /// This will not enable the contact options if it’s disabled in the config.
  var messagingEnabled: Bool? = nil
  /// Disable the Chat integration manually if it’s enabled in the Beacon config.
  /// This will not enable Chat if it’s disabled in the config.
  var chatEnabled: Bool? = nil
  /// Disable previous messages manually if messaging is enabled in the Beacon config.
  var enablePreviousMessages: Bool
  /// If your Beacon has Docs and Messaging (email or chat) enabled, this mode controls the user experience of the beacon
  var focusMode: HSBeaconFocusMode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HSBeaconSettings? {
    let beaconId = pigeonVar_list[0] as! String
    let debugLogging = pigeonVar_list[1] as! Bool
    let beaconTitle: String? = nilOrValue(pigeonVar_list[2])
    let docsEnabled: Bool? = nilOrValue(pigeonVar_list[3])
    let messagingEnabled: Bool? = nilOrValue(pigeonVar_list[4])
    let chatEnabled: Bool? = nilOrValue(pigeonVar_list[5])
    let enablePreviousMessages = pigeonVar_list[6] as! Bool
    let focusMode: HSBeaconFocusMode? = nilOrValue(pigeonVar_list[7])

    return HSBeaconSettings(
      beaconId: beaconId,
      debugLogging: debugLogging,
      beaconTitle: beaconTitle,
      docsEnabled: docsEnabled,
      messagingEnabled: messagingEnabled,
      chatEnabled: chatEnabled,
      enablePreviousMessages: enablePreviousMessages,
      focusMode: focusMode
    )
  }
  func toList() -> [Any?] {
    return [
      beaconId,
      debugLogging,
      beaconTitle,
      docsEnabled,
      messagingEnabled,
      chatEnabled,
      enablePreviousMessages,
      focusMode,
    ]
  }
  static func == (lhs: HSBeaconSettings, rhs: HSBeaconSettings) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.beaconId, rhs.beaconId) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.debugLogging, rhs.debugLogging) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.beaconTitle, rhs.beaconTitle) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.docsEnabled, rhs.docsEnabled) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.messagingEnabled, rhs.messagingEnabled) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.chatEnabled, rhs.chatEnabled) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.enablePreviousMessages, rhs.enablePreviousMessages) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.focusMode, rhs.focusMode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HSBeaconSettings")
    HelpScoutBeaconApiPigeonInternal.deepHash(value: beaconId, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: debugLogging, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: beaconTitle, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: docsEnabled, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: messagingEnabled, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: chatEnabled, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: enablePreviousMessages, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: focusMode, hasher: &hasher)
  }

  public var description: String {
    return "HSBeaconSettings(beaconId: \(String(describing: beaconId)), debugLogging: \(String(describing: debugLogging)), beaconTitle: \(String(describing: beaconTitle)), docsEnabled: \(String(describing: docsEnabled)), messagingEnabled: \(String(describing: messagingEnabled)), chatEnabled: \(String(describing: chatEnabled)), enablePreviousMessages: \(String(describing: enablePreviousMessages)), focusMode: \(String(describing: focusMode)))"
  }
}

/// Beacon user
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-user/index.html
/// * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconUser.html
///
/// Generated class from Pigeon that represents data sent in messages.
struct HSBeaconUser: Hashable, CustomStringConvertible {
  /// The email address for the current user.
  var email: String
  /// The name of the current user.
  var name: String? = nil
  /// The company of the current user. The max length of this value is 60 and will be truncated to fit.
  var company: String? = nil
  /// The job title of the current user. The max length of this value is 60 and will be truncated to fit.
  var jobTitle: String? = nil
  /// The URL to the avatar of the current user. The max length of this value is 200 and will not be set if the absoluteString exceeds that length.
  var avatar: String? = nil
  /// The attributes for the current user. These are arbitrary key/value pairs that will be sent to Help Scout to help identify the current user. You may add up to 30 different attributes.
  var attributes: [String: String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HSBeaconUser? {
    let email = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let company: String? = nilOrValue(pigeonVar_list[2])
    let jobTitle: String? = nilOrValue(pigeonVar_list[3])
    let avatar: String? = nilOrValue(pigeonVar_list[4])
    let attributes: [String: String]? = nilOrValue(pigeonVar_list[5])

    return HSBeaconUser(
      email: email,
      name: name,
      company: company,
      jobTitle: jobTitle,
      avatar: avatar,
      attributes: attributes
    )
  }
  func toList() -> [Any?] {
    return [
      email,
      name,
      company,
      jobTitle,
      avatar,
      attributes,
    ]
  }
  static func == (lhs: HSBeaconUser, rhs: HSBeaconUser) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.email, rhs.email) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.name, rhs.name) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.company, rhs.company) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.jobTitle, rhs.jobTitle) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.avatar, rhs.avatar) && HelpScoutBeaconApiPigeonInternal.deepEquals(lhs.attributes, rhs.attributes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HSBeaconUser")
    HelpScoutBeaconApiPigeonInternal.deepHash(value: email, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: name, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: company, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: jobTitle, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: avatar, hasher: &hasher)
    HelpScoutBeaconApiPigeonInternal.deepHash(value: attributes, hasher: &hasher)
  }

  public var description: String {
    return "HSBeaconUser(email: \(String(describing: email)), name: \(String(describing: name)), company: \(String(describing: company)), jobTitle: \(String(describing: jobTitle)), avatar: \(String(describing: avatar)), attributes: \(String(describing: attributes)))"
  }
}

private class HelpScoutBeaconApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HSBeaconRoute(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HSBeaconFocusMode(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return HSBeaconSettings.fromList(self.readValue() as! [Any?])
    case 132:
      return HSBeaconUser.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HelpScoutBeaconApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HSBeaconRoute {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HSBeaconFocusMode {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? HSBeaconSettings {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? HSBeaconUser {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HelpScoutBeaconApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HelpScoutBeaconApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HelpScoutBeaconApiPigeonCodecWriter(data: data)
  }
}

class HelpScoutBeaconApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HelpScoutBeaconApiPigeonCodec(readerWriter: HelpScoutBeaconApiPigeonCodecReaderWriter())
}

/// Help Scout Beacon API
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HelpScoutBeaconApi {
  /// Initialize the beacon with a beaconId and optional settings
  func setup(settings: HSBeaconSettings) throws
  /// Signs in with a Beacon user. This gives Beacon access to the user’s name, email address, and signature.
  func identify(beaconUser: HSBeaconUser) throws
  /// Opens the Beacon SDK from a specific view controller. The Beacon view controller will be presented as a modal.
  func open(settings: HSBeaconSettings, route: HSBeaconRoute, parameter: String?) throws
  func prefillContactForm(subject: String?, message: String?, attachments: [String]?) throws
  /// Logs the current Beacon user out and clears out their information from local storage.
  func clear() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HelpScoutBeaconApiSetup {
  static var codec: FlutterStandardMessageCodec { HelpScoutBeaconApiPigeonCodec.shared }
  /// Sets up an instance of `HelpScoutBeaconApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HelpScoutBeaconApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialize the beacon with a beaconId and optional settings
    let setupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.setup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! HSBeaconSettings
        do {
          try api.setup(settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setupChannel.setMessageHandler(nil)
    }
    /// Signs in with a Beacon user. This gives Beacon access to the user’s name, email address, and signature.
    let identifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.identify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      identifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let beaconUserArg = args[0] as! HSBeaconUser
        do {
          try api.identify(beaconUser: beaconUserArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      identifyChannel.setMessageHandler(nil)
    }
    /// Opens the Beacon SDK from a specific view controller. The Beacon view controller will be presented as a modal.
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! HSBeaconSettings
        let routeArg = args[1] as! HSBeaconRoute
        let parameterArg: String? = nilOrValue(args[2])
        do {
          try api.open(settings: settingsArg, route: routeArg, parameter: parameterArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let prefillContactFormChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.prefillContactForm\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prefillContactFormChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let subjectArg: String? = nilOrValue(args[0])
        let messageArg: String? = nilOrValue(args[1])
        let attachmentsArg: [String]? = nilOrValue(args[2])
        do {
          try api.prefillContactForm(subject: subjectArg, message: messageArg, attachments: attachmentsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      prefillContactFormChannel.setMessageHandler(nil)
    }
    /// Logs the current Beacon user out and clears out their information from local storage.
    let clearChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.clear\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearChannel.setMessageHandler { _, reply in
        do {
          try api.clear()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearChannel.setMessageHandler(nil)
    }
  }
}
