// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Beacon route/screen
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
enum HSBeaconRoute {
  /// Opens to the Home (Ask/Answers) screen (default value)
  ask,
  /// Chat screen
  chat,
  /// Open docs with optional search parameter (requires docs enabled and optionally a search param)
  docs,
  /// Article screen (requires an Article ID and docs enabled)
  article,
  /// Contact form (requires messaging enabled)
  contactForm,
  /// Previous Messages if any exist.
  previousMessages,
}

/// HSBeaconFocusMode represents various configuration modes of Beacon. Allowing you to customize the experience your users have, from getting in contact right away, to a more self service approach.
/// * More info is available AT https://docs.helpscout.com/article/1296-work-with-beacon-modes
enum HSBeaconFocusMode {
  /// An option to see both help articles and contact options side by side
  neutral,
  /// An option to see help articles first and contact options after interacting with content
  selfService,
  /// An option to see contact options first and help articles second
  askFirst,
}

/// Beacon Settings overrides
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
/// * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconSettings.html
class HSBeaconSettings {
  HSBeaconSettings({
    required this.beaconId,
    this.debugLogging = false,
    this.beaconTitle,
    this.docsEnabled,
    this.messagingEnabled,
    this.chatEnabled,
    this.enablePreviousMessages = true,
    this.focusMode,
  });

  /// The Beacon ID to use.
  String beaconId;

  /// Turn Logging on/off (should be disabled in production)
  ///
  /// Android only: neither the iOS Beacon SDK nor the JS Beacon exposes a logging switch.
  bool debugLogging;

  /// The title used in the main Beacon interface. This is Support by default.
  ///
  /// Has no effect on any platform — the title is controlled by the Beacon Builder config.
  /// The iOS SDK deprecated its equivalent property for the same reason.
  String? beaconTitle;

  /// Disable the Docs integration manually if it’s enabled in the Beacon config.
  /// This will not enable Docs if it’s disabled in the config.
  bool? docsEnabled;

  /// Disable the contact options manually if it’s enabled in the Beacon config.
  /// This will not enable the contact options if it’s disabled in the config.
  bool? messagingEnabled;

  /// Disable the Chat integration manually if it’s enabled in the Beacon config.
  /// This will not enable Chat if it’s disabled in the config.
  bool? chatEnabled;

  /// Disable previous messages manually if messaging is enabled in the Beacon config.
  bool enablePreviousMessages;

  /// If your Beacon has Docs and Messaging (email or chat) enabled, this mode controls the user experience of the beacon
  HSBeaconFocusMode? focusMode;

  List<Object?> _toList() {
    return <Object?>[
      beaconId,
      debugLogging,
      beaconTitle,
      docsEnabled,
      messagingEnabled,
      chatEnabled,
      enablePreviousMessages,
      focusMode,
    ];
  }

  Object encode() {
    return _toList();  }

  static HSBeaconSettings decode(Object result) {
    result as List<Object?>;
    return HSBeaconSettings(
      beaconId: result[0]! as String,
      debugLogging: result[1]! as bool,
      beaconTitle: result[2] as String?,
      docsEnabled: result[3] as bool?,
      messagingEnabled: result[4] as bool?,
      chatEnabled: result[5] as bool?,
      enablePreviousMessages: result[6]! as bool,
      focusMode: result[7] as HSBeaconFocusMode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HSBeaconSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(beaconId, other.beaconId) && _deepEquals(debugLogging, other.debugLogging) && _deepEquals(beaconTitle, other.beaconTitle) && _deepEquals(docsEnabled, other.docsEnabled) && _deepEquals(messagingEnabled, other.messagingEnabled) && _deepEquals(chatEnabled, other.chatEnabled) && _deepEquals(enablePreviousMessages, other.enablePreviousMessages) && _deepEquals(focusMode, other.focusMode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HSBeaconSettings(beaconId: $beaconId, debugLogging: $debugLogging, beaconTitle: $beaconTitle, docsEnabled: $docsEnabled, messagingEnabled: $messagingEnabled, chatEnabled: $chatEnabled, enablePreviousMessages: $enablePreviousMessages, focusMode: $focusMode)';
  }
}

/// Beacon user
/// * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-user/index.html
/// * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconUser.html
class HSBeaconUser {
  HSBeaconUser({
    required this.email,
    this.name,
    this.company,
    this.jobTitle,
    this.avatar,
    this.attributes,
  });

  /// The email address for the current user.
  String email;

  /// The name of the current user.
  String? name;

  /// The company of the current user. The max length of this value is 60 and will be truncated to fit.
  String? company;

  /// The job title of the current user. The max length of this value is 60 and will be truncated to fit.
  String? jobTitle;

  /// The URL to the avatar of the current user. The max length of this value is 200 and will not be set if the absoluteString exceeds that length.
  String? avatar;

  /// The attributes for the current user. These are arbitrary key/value pairs that will be sent to Help Scout to help identify the current user. You may add up to 30 different attributes.
  Map<Object?, Object?>? attributes;

  List<Object?> _toList() {
    return <Object?>[
      email,
      name,
      company,
      jobTitle,
      avatar,
      attributes,
    ];
  }

  Object encode() {
    return _toList();  }

  static HSBeaconUser decode(Object result) {
    result as List<Object?>;
    return HSBeaconUser(
      email: result[0]! as String,
      name: result[1] as String?,
      company: result[2] as String?,
      jobTitle: result[3] as String?,
      avatar: result[4] as String?,
      attributes: result[5] as Map<Object?, Object?>?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HSBeaconUser || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(email, other.email) && _deepEquals(name, other.name) && _deepEquals(company, other.company) && _deepEquals(jobTitle, other.jobTitle) && _deepEquals(avatar, other.avatar) && _deepEquals(attributes, other.attributes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HSBeaconUser(email: $email, name: $name, company: $company, jobTitle: $jobTitle, avatar: $avatar, attributes: $attributes)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is HSBeaconRoute) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is HSBeaconFocusMode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is HSBeaconSettings) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is HSBeaconUser) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : HSBeaconRoute.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : HSBeaconFocusMode.values[value];
      case 131:
        return HSBeaconSettings.decode(readValue(buffer)!);
      case 132:
        return HSBeaconUser.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Help Scout Beacon API
class HelpScoutBeaconApi {
  /// Constructor for [HelpScoutBeaconApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HelpScoutBeaconApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Initialize the beacon with a beaconId and optional settings
  Future<void> setup({required HSBeaconSettings settings}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.setup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[settings]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Signs in with a Beacon user. This gives Beacon access to the user’s name, email address, and signature.
  Future<void> identify({required HSBeaconUser beaconUser}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.identify$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[beaconUser]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Opens the Beacon SDK from a specific view controller. The Beacon view controller will be presented as a modal.
  Future<void> open({required HSBeaconSettings settings, HSBeaconRoute route = HSBeaconRoute.ask, String? parameter, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[settings, route, parameter]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> prefillContactForm(String? subject, String? message, List<String>? attachments) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.prefillContactForm$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[subject, message, attachments]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Logs the current Beacon user out and clears out their information from local storage.
  Future<void> clear() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.clear$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
