// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object HelpScoutBeaconApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Beacon route/screen
 * * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
 */
enum class HSBeaconRoute(val raw: Int) {
  /** Opens to the Home (Ask/Answers) screen (default value) */
  ASK(0),
  /** Chat screen */
  CHAT(1),
  /** Open docs with optional search parameter (requires docs enabled and optionally a search param) */
  DOCS(2),
  /** Article screen (requires an Article ID and docs enabled) */
  ARTICLE(3),
  /** Contact form (requires messaging enabled) */
  CONTACT_FORM(4),
  /** Previous Messages if any exist. */
  PREVIOUS_MESSAGES(5);

  companion object {
    fun ofRaw(raw: Int): HSBeaconRoute? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * HSBeaconFocusMode represents various configuration modes of Beacon. Allowing you to customize the experience your users have, from getting in contact right away, to a more self service approach.
 * * More info is available AT https://docs.helpscout.com/article/1296-work-with-beacon-modes
 */
enum class HSBeaconFocusMode(val raw: Int) {
  /** An option to see both help articles and contact options side by side */
  NEUTRAL(0),
  /** An option to see help articles first and contact options after interacting with content */
  SELF_SERVICE(1),
  /** An option to see contact options first and help articles second */
  ASK_FIRST(2);

  companion object {
    fun ofRaw(raw: Int): HSBeaconFocusMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Beacon Settings overrides
 * * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
 * * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconSettings.html
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HSBeaconSettings (
  /** The Beacon ID to use. */
  val beaconId: String,
  /** Turn Logging on/off (should be disabled in production) */
  val debugLogging: Boolean,
  /** The title used in the main Beacon interface. This is Support by default. */
  val beaconTitle: String? = null,
  /**
   * Disable the Docs integration manually if it’s enabled in the Beacon config.
   * This will not enable Docs if it’s disabled in the config.
   */
  val docsEnabled: Boolean? = null,
  /**
   * Disable the contact options manually if it’s enabled in the Beacon config.
   * This will not enable the contact options if it’s disabled in the config.
   */
  val messagingEnabled: Boolean? = null,
  /**
   * Disable the Chat integration manually if it’s enabled in the Beacon config.
   * This will not enable Chat if it’s disabled in the config.
   */
  val chatEnabled: Boolean? = null,
  /** Disable previous messages manually if messaging is enabled in the Beacon config. */
  val enablePreviousMessages: Boolean,
  /** If your Beacon has Docs and Messaging (email or chat) enabled, this mode controls the user experience of the beacon */
  val focusMode: HSBeaconFocusMode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HSBeaconSettings {
      val beaconId = pigeonVar_list[0] as String
      val debugLogging = pigeonVar_list[1] as Boolean
      val beaconTitle = pigeonVar_list[2] as String?
      val docsEnabled = pigeonVar_list[3] as Boolean?
      val messagingEnabled = pigeonVar_list[4] as Boolean?
      val chatEnabled = pigeonVar_list[5] as Boolean?
      val enablePreviousMessages = pigeonVar_list[6] as Boolean
      val focusMode = pigeonVar_list[7] as HSBeaconFocusMode?
      return HSBeaconSettings(beaconId, debugLogging, beaconTitle, docsEnabled, messagingEnabled, chatEnabled, enablePreviousMessages, focusMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      beaconId,
      debugLogging,
      beaconTitle,
      docsEnabled,
      messagingEnabled,
      chatEnabled,
      enablePreviousMessages,
      focusMode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HSBeaconSettings
    return HelpScoutBeaconApiPigeonUtils.deepEquals(this.beaconId, other.beaconId) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.debugLogging, other.debugLogging) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.beaconTitle, other.beaconTitle) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.docsEnabled, other.docsEnabled) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.messagingEnabled, other.messagingEnabled) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.chatEnabled, other.chatEnabled) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.enablePreviousMessages, other.enablePreviousMessages) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.focusMode, other.focusMode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.beaconId)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.debugLogging)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.beaconTitle)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.docsEnabled)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.messagingEnabled)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.chatEnabled)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.enablePreviousMessages)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.focusMode)
    return result
  }
  override fun toString(): String {
    return "HSBeaconSettings(beaconId=$beaconId, debugLogging=$debugLogging, beaconTitle=$beaconTitle, docsEnabled=$docsEnabled, messagingEnabled=$messagingEnabled, chatEnabled=$chatEnabled, enablePreviousMessages=$enablePreviousMessages, focusMode=$focusMode)"
  }
}

/**
 * Beacon user
 * * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-user/index.html
 * * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconUser.html
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HSBeaconUser (
  /** The email address for the current user. */
  val email: String,
  /** The name of the current user. */
  val name: String? = null,
  /** The company of the current user. The max length of this value is 60 and will be truncated to fit. */
  val company: String? = null,
  /** The job title of the current user. The max length of this value is 60 and will be truncated to fit. */
  val jobTitle: String? = null,
  /** The URL to the avatar of the current user. The max length of this value is 200 and will not be set if the absoluteString exceeds that length. */
  val avatar: String? = null,
  /** The attributes for the current user. These are arbitrary key/value pairs that will be sent to Help Scout to help identify the current user. You may add up to 30 different attributes. */
  val attributes: Map<Any, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HSBeaconUser {
      val email = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val company = pigeonVar_list[2] as String?
      val jobTitle = pigeonVar_list[3] as String?
      val avatar = pigeonVar_list[4] as String?
      val attributes = pigeonVar_list[5] as Map<Any, Any?>?
      return HSBeaconUser(email, name, company, jobTitle, avatar, attributes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      email,
      name,
      company,
      jobTitle,
      avatar,
      attributes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HSBeaconUser
    return HelpScoutBeaconApiPigeonUtils.deepEquals(this.email, other.email) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.name, other.name) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.company, other.company) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.jobTitle, other.jobTitle) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.avatar, other.avatar) && HelpScoutBeaconApiPigeonUtils.deepEquals(this.attributes, other.attributes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.email)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.name)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.company)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.jobTitle)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.avatar)
    result = 31 * result + HelpScoutBeaconApiPigeonUtils.deepHash(this.attributes)
    return result
  }
  override fun toString(): String {
    return "HSBeaconUser(email=$email, name=$name, company=$company, jobTitle=$jobTitle, avatar=$avatar, attributes=$attributes)"
  }
}
private open class HelpScoutBeaconApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HSBeaconRoute.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HSBeaconFocusMode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HSBeaconSettings.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HSBeaconUser.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HSBeaconRoute -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is HSBeaconFocusMode -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is HSBeaconSettings -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is HSBeaconUser -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Help Scout Beacon API
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HelpScoutBeaconApi {
  /** Initialize the beacon with a beaconId and optional settings */
  fun setup(settings: HSBeaconSettings)
  /** Signs in with a Beacon user. This gives Beacon access to the user’s name, email address, and signature. */
  fun identify(beaconUser: HSBeaconUser)
  /** Opens the Beacon SDK from a specific view controller. The Beacon view controller will be presented as a modal. */
  fun open(settings: HSBeaconSettings, route: HSBeaconRoute, parameter: String?)
  fun prefillContactForm(subject: String?, message: String?, attachments: List<String>?)
  /** Logs the current Beacon user out and clears out their information from local storage. */
  fun clear()

  companion object {
    /** The codec used by HelpScoutBeaconApi. */
    val codec: MessageCodec<Any?> by lazy {
      HelpScoutBeaconApiPigeonCodec()
    }
    /** Sets up an instance of `HelpScoutBeaconApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HelpScoutBeaconApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.setup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as HSBeaconSettings
            val wrapped: List<Any?> = try {
              api.setup(settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.identify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val beaconUserArg = args[0] as HSBeaconUser
            val wrapped: List<Any?> = try {
              api.identify(beaconUserArg)
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as HSBeaconSettings
            val routeArg = args[1] as HSBeaconRoute
            val parameterArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.open(settingsArg, routeArg, parameterArg)
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.prefillContactForm$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val subjectArg = args[0] as String?
            val messageArg = args[1] as String?
            val attachmentsArg = args[2] as List<String>?
            val wrapped: List<Any?> = try {
              api.prefillContactForm(subjectArg, messageArg, attachmentsArg)
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.clear$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clear()
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
