// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object HelpScoutBeaconApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Beacon route/screen
 * * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
 */
enum class HSBeaconRoute(val raw: Int) {
  /** Opens to the Home (Ask/Answers) screen (default value) */
  ASK(0),
  /** Chat screen */
  CHAT(1),
  /** Open docs with optional search parameter (requires docs enabled and optionally a search param) */
  DOCS(2),
  /** Article screen (requires an Article ID and docs enabled) */
  ARTICLE(3),
  /** Contact form (requires messaging enabled) */
  CONTACT_FORM(4),
  /** Previous Messages if any exist. */
  PREVIOUS_MESSAGES(5);

  companion object {
    fun ofRaw(raw: Int): HSBeaconRoute? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * HSBeaconFocusMode represents various configuration modes of Beacon. Allowing you to customize the experience your users have, from getting in contact right away, to a more self service approach.
 * * More info is available AT https://docs.helpscout.com/article/1296-work-with-beacon-modes
 */
enum class HSBeaconFocusMode(val raw: Int) {
  /** An option to see both help articles and contact options side by side */
  NEUTRAL(0),
  /** An option to see help articles first and contact options after interacting with content */
  SELF_SERVICE(1),
  /** An option to see contact options first and help articles second */
  ASK_FIRST(2);

  companion object {
    fun ofRaw(raw: Int): HSBeaconFocusMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Beacon Settings overrides
 * * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-screens/index.html
 * * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconSettings.html
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HSBeaconSettings (
  /** The Beacon ID to use. */
  val beaconId: String,
  /** Turn Logging on/off (should be disabled in production) */
  val debugLogging: Boolean,
  /** The title used in the main Beacon interface. This is Support by default. */
  val beaconTitle: String? = null,
  /**
   * Disable the Docs integration manually if it’s enabled in the Beacon config.
   * This will not enable Docs if it’s disabled in the config.
   */
  val docsEnabled: Boolean? = null,
  /**
   * Disable the contact options manually if it’s enabled in the Beacon config.
   * This will not enable the contact options if it’s disabled in the config.
   */
  val messagingEnabled: Boolean? = null,
  /**
   * Disable the Chat integration manually if it’s enabled in the Beacon config.
   * This will not enable Chat if it’s disabled in the config.
   */
  val chatEnabled: Boolean? = null,
  /** Disable previous messages manually if messaging is enabled in the Beacon config. */
  val enablePreviousMessages: Boolean,
  /** If your Beacon has Docs and Messaging (email or chat) enabled, this mode controls the user experience of the beacon */
  val focusMode: HSBeaconFocusMode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HSBeaconSettings {
      val beaconId = pigeonVar_list[0] as String
      val debugLogging = pigeonVar_list[1] as Boolean
      val beaconTitle = pigeonVar_list[2] as String?
      val docsEnabled = pigeonVar_list[3] as Boolean?
      val messagingEnabled = pigeonVar_list[4] as Boolean?
      val chatEnabled = pigeonVar_list[5] as Boolean?
      val enablePreviousMessages = pigeonVar_list[6] as Boolean
      val focusMode = pigeonVar_list[7] as HSBeaconFocusMode?
      return HSBeaconSettings(beaconId, debugLogging, beaconTitle, docsEnabled, messagingEnabled, chatEnabled, enablePreviousMessages, focusMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      beaconId,
      debugLogging,
      beaconTitle,
      docsEnabled,
      messagingEnabled,
      chatEnabled,
      enablePreviousMessages,
      focusMode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HSBeaconSettings) {
      return false
    }
    if (this === other) {
      return true
    }
    return HelpScoutBeaconApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Beacon user
 * * https://developer.helpscout.com/beacon-2/android-api/beacon/com.helpscout.beacon.model/-beacon-user/index.html
 * * https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconUser.html
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HSBeaconUser (
  /** The email address for the current user. */
  val email: String,
  /** The name of the current user. */
  val name: String? = null,
  /** The company of the current user. The max length of this value is 60 and will be truncated to fit. */
  val company: String? = null,
  /** The job title of the current user. The max length of this value is 60 and will be truncated to fit. */
  val jobTitle: String? = null,
  /** The URL to the avatar of the current user. The max length of this value is 200 and will not be set if the absoluteString exceeds that length. */
  val avatar: String? = null,
  /** The attributes for the current user. These are arbitrary key/value pairs that will be sent to Help Scout to help identify the current user. You may add up to 30 different attributes. */
  val attributes: Map<Any, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HSBeaconUser {
      val email = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val company = pigeonVar_list[2] as String?
      val jobTitle = pigeonVar_list[3] as String?
      val avatar = pigeonVar_list[4] as String?
      val attributes = pigeonVar_list[5] as Map<Any, Any?>?
      return HSBeaconUser(email, name, company, jobTitle, avatar, attributes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      email,
      name,
      company,
      jobTitle,
      avatar,
      attributes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HSBeaconUser) {
      return false
    }
    if (this === other) {
      return true
    }
    return HelpScoutBeaconApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class HelpScoutBeaconApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HSBeaconRoute.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HSBeaconFocusMode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HSBeaconSettings.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HSBeaconUser.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HSBeaconRoute -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is HSBeaconFocusMode -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is HSBeaconSettings -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is HSBeaconUser -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Help Scout Beacon API
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HelpScoutBeaconApi {
  /** Initialize the beacon with a beaconId and optional settings */
  fun setup(settings: HSBeaconSettings)
  /** Signs in with a Beacon user. This gives Beacon access to the user’s name, email address, and signature. */
  fun identify(beaconUser: HSBeaconUser)
  /** Opens the Beacon SDK from a specific view controller. The Beacon view controller will be presented as a modal. */
  fun open(settings: HSBeaconSettings, route: HSBeaconRoute, parameter: String?)
  fun prefillContactForm(subject: String?, message: String?, attachments: List<String>?)
  /** Logs the current Beacon user out and clears out their information from local storage. */
  fun clear()

  companion object {
    /** The codec used by HelpScoutBeaconApi. */
    val codec: MessageCodec<Any?> by lazy {
      HelpScoutBeaconApiPigeonCodec()
    }
    /** Sets up an instance of `HelpScoutBeaconApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HelpScoutBeaconApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.setup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as HSBeaconSettings
            val wrapped: List<Any?> = try {
              api.setup(settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.identify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val beaconUserArg = args[0] as HSBeaconUser
            val wrapped: List<Any?> = try {
              api.identify(beaconUserArg)
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as HSBeaconSettings
            val routeArg = args[1] as HSBeaconRoute
            val parameterArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.open(settingsArg, routeArg, parameterArg)
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.prefillContactForm$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val subjectArg = args[0] as String?
            val messageArg = args[1] as String?
            val attachmentsArg = args[2] as List<String>?
            val wrapped: List<Any?> = try {
              api.prefillContactForm(subjectArg, messageArg, attachmentsArg)
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.help_scout_beacon.HelpScoutBeaconApi.clear$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clear()
              listOf(null)
            } catch (exception: Throwable) {
              HelpScoutBeaconApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
